name: nutricional
description: "Plataforma Nutricional con Men√∫ Semanal + QR"
publish_to: 'none'
version: 1.3.5+10

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^6.1.1
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.1.5
  cloudinary_flutter: ^1.3.0
  cloudinary_public: ^0.23.1
  provider: ^6.1.5+1
  image_picker: ^1.2.1
  http: ^1.1.0
  sqflite: ^2.3.0
  path: ^1.9.0
  connectivity_plus: ^5.0.2
  flutter_secure_storage: ^9.0.0
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.0
  intl: ^0.19.0
  mobile_scanner: ^5.0.0
  uuid: ^4.5.1
  firebase_messaging: ^16.1.1
  cached_network_image: ^3.3.1
  pdf: ^3.11.1
  printing: ^5.13.2
  path_provider: ^2.1.4
  url_launcher: ^6.3.1
  crypto: ^3.0.3
  introduction_screen: ^3.1.14
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/image/
